//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parcels
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Parcels()
        {
            this.ParcelsHistory = new HashSet<ParcelsHistory>();
        }
    
        public long Id { get; set; }
        public int SentFromPostOfficeId { get; set; }
        public int SentToPostOfficeId { get; set; }
        public long SentFromPersonId { get; set; }
        public long SentToPersonId { get; set; }
        public long DriverId { get; set; }
        public long EmployeeId { get; set; }
        public long TypeId { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<bool> SignatureByEmployee { get; set; }
        public Nullable<bool> SignatureByCustomer { get; set; }
        public long StatusId { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Customers Customers1 { get; set; }
        public virtual DeliveryStatus DeliveryStatus { get; set; }
        public virtual Drivers Drivers { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual PostOffices PostOffices { get; set; }
        public virtual PostOffices PostOffices1 { get; set; }
        public virtual Types Types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParcelsHistory> ParcelsHistory { get; set; }
    }
}
