//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PostEntities : DbContext
    {
        public PostEntities()
            : base("name=PostEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Addresses> Addresses { get; set; }
        public virtual DbSet<Cars> Cars { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<DeliveryStatus> DeliveryStatus { get; set; }
        public virtual DbSet<Drivers> Drivers { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Parcels> Parcels { get; set; }
        public virtual DbSet<ParcelsHistory> ParcelsHistory { get; set; }
        public virtual DbSet<People> People { get; set; }
        public virtual DbSet<PostOffices> PostOffices { get; set; }
        public virtual DbSet<Types> Types { get; set; }
    }
}
